services:
  - type: web
    name: spam-detector
    env: python
    plan: free
    # Added 'set -o pipefail' to make sure errors in the pipeline stop the build
    buildRoot: .
    buildCommand: "set -o pipefail && pip install -r requirements.txt && python pipeline.py"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: spam-db
          property: connectionString

databases:
  - name: spam-db
    plan: free