services:
  # A Web Service for our Flask App
  - type: web
    name: spam-detector
    env: python
    plan: free
    # Run the pipeline to create the models, then install requirements
    buildCommand: "python pipeline.py && pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: spam-db
          property: connectionString

databases:
  # A PostgreSQL Database
  - name: spam-db
    plan: free
